global:
  scrape_interval:     15s
  evaluation_interval: 15s

#rule_files: 
#   - "/etc/prometheus/alert.rules.yml"

scrape_configs:
  - job_name: 'game-service'
    scheme: https
    tls_config:
     insecure_skip_verify: true
     #ca_file: /Users/charters/Repositories/github/nottycode/cloud-native-examples/serviceC/target/liberty/wlp/usr/servers/serviceCServer/resources/security/liberty.crt
    basic_auth:
      username: 'admin'
      password: 'adminadmin'
    static_configs:
      - targets: ['localhost:9445']
        labels:
          group: 'liberty'

#  - job_name: 'prometheus'
#    static_configs:
#      - targets: ['localhost:9090']
#        labels:
#          group: 'prometheus'

